In [12]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [4]:
statistics

<module 'statistics' from '/Users/melawai.it/anaconda3/lib/python3.11/statistics.py'>

In [5]:
import numpy as np

In [8]:
arr = (np.random.random(6) * 10).astype(int)

In [9]:
arr

array([9, 4, 3, 1, 9, 7])

In [10]:
hmean = statistics.harmonic_mean(arr)

In [11]:
hmean

3.079429735234216

# Start from Here

# Meaaure of Tendency

## Mean

In [13]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan,4, 28.0]

In [14]:
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [15]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

In [16]:
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [17]:
mean_ = sum(x)/len(x)
mean_

8.7

In [18]:
mean_ = statistics.mean(x)
mean_

8.7

In [19]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [21]:
mean_ = np.mean(y)
mean_

8.7

In [23]:
mean_ = y.mean()
mean_

8.7

In [24]:
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [26]:
print(np.nanmean(y_with_nan))

8.7


In [27]:
mean_ = z.mean()
mean_

8.7

In [28]:
z_with_nan.mean()

8.7

## Weighted Mean

In [29]:
.2*2 + .5*4 + .3*8

4.8

In [31]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [.1, .2, .3, .25, .15]

wmean1 = sum(w[i]*x[i] for i in range(len(x))) / sum(w)

wmean2 = sum(w_*x_ for w_,x_ in zip(w,x)) / sum(w)

print(wmean1)
print(wmean2)

6.95
6.95


In [32]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

In [33]:
wmean3 = np.average(y, weights=w)

wmean4 = np.average(z, weights=w)

print(wmean3)
print(wmean4)

6.95
6.95


In [34]:
(w*y).sum() / w.sum()

6.95

## Harmonic Mean

In [35]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [36]:
hmean_s = statistics.harmonic_mean(x)
hmean_s

2.7613412228796843

In [37]:
scipy.stats.hmean(y)

2.7613412228796843

In [38]:
scipy.stats.hmean(z)

2.7613412228796843

## Geometric Mean

In [39]:
arr = np.array([1,2,3])

In [41]:
gmean = 1
for i in arr:
    gmean *= i

gmean **= 1/len(arr)
gmean

1.8171205928321397

In [42]:
gmean = 1
for item in x:
    gmean *= item

gmean **= 1/len(x)
gmean

4.677885674856041

In [43]:
scipy.stats.gmean(y)

4.67788567485604

In [44]:
scipy.stats.gmean(z)

4.67788567485604

## Median

In [46]:
n = len(x)

if n % 2:
    median_ = sorted(x)[round(0.5*n-1)]
else:
    x_ord, index = sorted(x), round(.5 * n)
    median_ = .5 * (x_ord[index-1] + x_ord[index])
    
median_

4

In [47]:
x

[8.0, 1, 2.5, 4, 28.0]

In [48]:
statistics.median_low(x[:-1])

2.5

In [49]:
statistics.median_high(x[:-1])

4

In [50]:
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

6.0
4
8.0


In [52]:
median_ = np.median(y)
median_

4.0

In [53]:
median_ = np.median(y[:-1])
median_

3.25

## Mode

In [60]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

In [56]:
[(u.count(item), item) for item in set(u)]

[(1, 8), (2, 2), (1, 3), (1, 12)]

In [58]:
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [59]:
mode_s = statistics.mode(u)
mode_s

2

In [63]:
u, v = np.array(u), np.array(v)

In [64]:
scipy.stats.mode(u)

/var/folders/pw/z_nfq_0j4g3ckjz532ktnkjm0000gn/T/ipykernel_1921/2148263613.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(u)


ModeResult(mode=array([2]), count=array([2]))

In [66]:
mode_ = scipy.stats.mode(v)

/var/folders/pw/z_nfq_0j4g3ckjz532ktnkjm0000gn/T/ipykernel_1921/2462390298.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_ = scipy.stats.mode(v)


In [67]:
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [68]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [69]:
print(u.mode())
print(v.mode())
print(w.mode())

0    2
dtype: int64
0    12
1    15
dtype: int64
0    2.0
dtype: float64


# Measure of Variability

<ul>
    <li> Variance </li>
    <li> Standard deviation </li>
    <li> Skewness </li>
    <li> Percentile </li>
    <li> Range </li>
</ul>

## Variance

In [70]:
x

[8.0, 1, 2.5, 4, 28.0]

In [71]:
n = len(x)

mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / (n - 1)

var_

123.19999999999999

In [73]:
var_s = statistics.variance(x)
var_s

123.2

In [74]:
var_np = np.var(y, ddof=1)
var_np

123.19999999999999

In [76]:
print(np.var.__doc__)


    Compute the variance along the specified axis.

    Returns the variance of the array elements, a measure of the spread of a
    distribution.  The variance is computed for the flattened array by
    default, otherwise over the specified axis.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose variance is desired.  If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the variance is computed.  The default is to
        compute the variance of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a variance is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the variance.  For arrays of integer type
        the default is `float64`; for arrays of float types it is the same as
        the array type.
    out : ndarray

In [77]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [78]:
z.var(ddof=1)

123.19999999999999

In [ ]:
n = len(x)

mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / n

var_

In [ ]:
var_s = statistics.pvariance(x)
var_s

In [ ]:
var_ = y.var(ddof=0)
var_

In [ ]:
z.var(ddof=0)

## Standard Deviation

In [80]:
var_

123.19999999999999

In [82]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [83]:
std_s = statistics.stdev(x)
std_s

11.099549540409287

In [84]:
np.std(y, ddof=1)

11.099549540409285

In [85]:
y.std(ddof=1)

11.099549540409285

In [86]:
z.std(ddof=1)

11.099549540409285

## Skewness

In [87]:
x

[8.0, 1, 2.5, 4, 28.0]

In [88]:
n = len(x)

mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = sum((item - mean_)**3 for item in x) * n / ((n-1) * (n-2) * (std_**3))

In [89]:
skew_

1.9470432273905929

In [90]:
print(y)
print(y_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]


In [91]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [92]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [93]:
print(z)
print(z_with_nan)

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [94]:
z.skew()

1.9470432273905924

In [95]:
z_with_nan.skew()

1.9470432273905924

## Percentile

In [96]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [97]:
statistics.quantiles(x, n=2)

[8.0]

In [99]:
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [132]:
y = np.array(x)

In [130]:
y

array([-5. , -1.1,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [131]:
np.percentile(y, 5)

-3.44

In [133]:
np.percentile(y, 95)

34.919999999999995

In [134]:
print(np.percentile(y, [25, 50, 75]))
print(np.median(y))

[ 0.1  8.  21. ]
8.0


In [135]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [137]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [139]:
print(np.quantile(y, 0.05))
print(np.quantile(y, 0.95))
print(np.quantile(y, [.25, .5, .75]))
print(np.nanquantile(y_with_nan, [.25, .5, .75]))

-3.44
34.919999999999995
[ 0.1  8.  21. ]
[ 0.1  8.  21. ]


In [140]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)

In [145]:
print(z.quantile(.05))
print(z.quantile(.95))
print(z.quantile([.25, .50, .75]))
print(z_with_nan.quantile([.25, .50, .75]))

-3.44
34.919999999999995
0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64
0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64


## Range

In [151]:
z_with_nan

0    -5.0
1    -1.1
2     NaN
3     0.1
4     2.0
5     8.0
6    12.8
7    21.0
8    25.8
9    41.0
dtype: float64

In [153]:
print(np.ptp(y))
print(y.ptp())
print(np.ptp(y_with_nan))
print(np.ptp(z))


46.0
46.0
nan
46.0


In [154]:
print(np.ptp(z_with_nan))

nan


In [155]:
type(z_with_nan)

pandas.core.series.Series

In [158]:
# Interquartil Range
quartile_y = np.quantile(y, [.25, .75])
print(quartile_y[1] - quartile_y[0])

quartile_z = z.quantile([.25, .75])
print(quartile_z[.75] - quartile_z[.25])

20.9
20.9


## Summary of Descriptive Sttistics

In [160]:
result = scipy.stats.describe(y, ddof=1, bias=False)
print(result)

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)


In [161]:
print(result.nobs)
print(result.minmax[0])
print(result.minmax[1])
print(result.mean)
print(result.variance)
print(result.skewness)
print(result.kurtosis)

9
-5.0
41.0
11.622222222222222
228.75194444444446
0.9249043136685094
0.14770623629658886


In [162]:
result = z.describe()
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [164]:
print(result['mean'])
print(result['std'])
print(result['min'])
print(result['max'])
print(result['25%'])
print(result['50%'])
print(result['75%'])

11.622222222222222
15.12454774346805
-5.0
41.0
0.1
8.0
21.0


In [167]:
result_2 = z.describe(percentiles = [.25, .5, .75, .95])
result_2

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
95%      34.920000
max      41.000000
dtype: float64

# Measure of Correlation between Pairs of Data

In [178]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [179]:
x_arr, y_arr = np.array(x), np.array(y)
x_ser, y_ser = pd.Series(x), pd.Series(y)

## Covariance

In [170]:
n = len(x)

mean_x, mean_y = sum(x) / n, sum(y) / n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n-1) )

cov_xy

19.95

In [171]:
cov_matrix = np.cov(x_arr, y_arr)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [172]:
cov_xy = cov_matrix[0,1]
cov_xy

19.95

In [173]:
cov_xy = x_ser.cov(y_ser)
cov_xy

19.95

## Correlation Coefficient

In [182]:
var_x = x_arr.var(ddof=1)
var_y = y_arr.var(ddof=1)

std_x = var_x ** 0.5
std_y = var_y ** 0.5

r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [183]:
print(var_x, var_y)

38.5 13.914285714285711


In [184]:
r, p = scipy.stats.pearsonr(x_arr, y_arr)
print(r, p)

0.8619500056316061 5.122760847201132e-07


In [185]:
corr_matrix = np.corrcoef(x_arr, y_arr)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [186]:
r = corr_matrix[0,1]
r

0.8619500056316061

In [188]:
result = scipy.stats.linregress(x_arr, y_arr)
result

LinregressResult(slope=0.5181818181818181, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [189]:
r = result.rvalue
r

0.861950005631606

In [190]:
r = x_ser.corr(y_ser)
r

0.8619500056316061

# Working with 2D Data

In [191]:
a = np.array([
    [1, 1, 1],
    [2, 3, 1],
    [4, 9, 2],
    [8,27, 4],
    [16,1, 1]
])

In [194]:
np.mean(a)

5.4

In [195]:
a.mean()

5.4

In [197]:
np.median(a)

2.0

In [198]:
a.var(ddof=1)

53.40000000000001

In [199]:
np.mean(a, axis=0)

array([6.2, 8.2, 1.8])

In [200]:
a.mean(axis=0)

array([6.2, 8.2, 1.8])

In [201]:
print(np.mean(a, axis=1))
print(a.mean(axis=1))

[ 1.  2.  5. 13.  6.]
[ 1.  2.  5. 13.  6.]


In [202]:
print(np.median(a, axis=0))
print(np.median(a, axis=1))
print(a.var(axis=0, ddof=1))
print(a.var(axis=1, ddof=1))

[4. 3. 1.]
[1. 2. 4. 8. 1.]
[ 37.2 121.2   1.7]
[  0.   1.  13. 151.  75.]


In [203]:
scipy.stats.gmean(a)

array([4.        , 3.73719282, 1.51571657])

In [204]:
scipy.stats.gmean(a, axis=0)

array([4.        , 3.73719282, 1.51571657])

In [205]:
scipy.stats.gmean(a, axis=1)

array([1.        , 1.81712059, 4.16016765, 9.52440631, 2.5198421 ])

In [206]:
scipy.stats.gmean(a, axis=None)

2.829705017016332

In [208]:
print(scipy.stats.describe(a, axis=None, ddof=1, bias=False))

DescribeResult(nobs=15, minmax=(1, 27), mean=5.4, variance=53.40000000000001, skewness=2.264965290423389, kurtosis=5.212690982795767)


In [209]:
print(scipy.stats.describe(a, ddof=1, bias=False))

DescribeResult(nobs=5, minmax=(array([1, 1, 1]), array([16, 27,  4])), mean=array([6.2, 8.2, 1.8]), variance=array([ 37.2, 121.2,   1.7]), skewness=array([1.32531471, 1.79809454, 1.71439233]), kurtosis=array([1.30376344, 3.14969121, 2.66435986]))


In [210]:
print(scipy.stats.describe(a, axis=1, ddof=1, bias=False))

DescribeResult(nobs=3, minmax=(array([1, 1, 2, 4, 1]), array([ 1,  3,  9, 27, 16])), mean=array([ 1.,  2.,  5., 13.,  6.]), variance=array([  0.,   1.,  13., 151.,  75.]), skewness=array([       nan, 0.        , 1.15206964, 1.52787436, 1.73205081]), kurtosis=array([ nan, -1.5, -1.5, -1.5, -1.5]))


/var/folders/pw/z_nfq_0j4g3ckjz532ktnkjm0000gn/T/ipykernel_1921/1433016387.py:1: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  print(scipy.stats.describe(a, axis=1, ddof=1, bias=False))
/Users/melawai.it/anaconda3/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1522: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  sk = skew(a, axis, bias=bias)
/Users/melawai.it/anaconda3/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1523: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurt = kurtosis(a, axis, bias=bias)


In [214]:
result = scipy.stats.describe(a, axis=1, ddof=1, bias=False)
result.mean

/var/folders/pw/z_nfq_0j4g3ckjz532ktnkjm0000gn/T/ipykernel_1921/4127661655.py:1: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  result = scipy.stats.describe(a, axis=1, ddof=1, bias=False)


array([ 1.,  2.,  5., 13.,  6.])

## Dataframe

In [215]:
row_names = ['first', 'second', 'third', 'fourth', 'fifth']
col_names = ['A', 'B', 'C']
df = pd.DataFrame(a, index=row_names, columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [216]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [217]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [218]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [220]:
df.var(axis=1)

first       0.0
second      1.0
third      13.0
fourth    151.0
fifth      75.0
dtype: float64

In [221]:
df['A']

first      1
second     2
third      4
fourth     8
fifth     16
Name: A, dtype: int64

In [222]:
df['A'].mean()

6.2

In [223]:
df['A'].var()

37.20000000000001

In [224]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [225]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [226]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000

In [227]:
df.describe().at['mean', 'A']

6.2

In [228]:
df.describe().at['50%', 'B']

3.0